---
title: "Epidemiología y Análisis de Datos en Salud en R"
subtitle: "Tutorial 1. Introducción a R"
author: "Zulma M. Cucunubá"
date: "24/10/2018"
output:
  rmarkdown::html_document:
    theme: cosmo
    toc: true
    toc_depth: 2
classoption: landscape
fontsize: 24pt


---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(Amelia)   # Permite identificar missing values
library(pscl)     # 
library(ROCR)     # Contiene las curvas ROC
library(corrplot) # Permite hacer correlaciones
library(aod)      # Contiene el Wald Test
library(tidyverse)
library(broom)
library(dplyr)

```

# Qué es R?

R es un software libre que permite realizar diversas tareas relacionadas con la ciencia de datos, las cuales incluyen entre otras:
- Manejo y organización de datos

- Análisis estadístico

- Modelización de datos

- Reportes automatizados

- Páginas Web

- Visualización estática

- Visaulizacion dinámica para plataformas interactivas de visualización como ShinyApp

- Interacción con otros lenguajes de programación (SQL, Bash, Phyton, C++, Stan, entre otros)

- Programación en equipo 

En resumen, los usos de R son diversos y crecientes en la medida en que se trata de un softare de programacion libre donde cualquier persona puede contribuir construyendo nuevos usos los cuales son de accesso libre.


# Porqué usar R en Epidemiología

Hay  una lista creciente de razones para usar R, listaré a continuación las cuatro razones que personalmente considero son las mas importantes y que están inter-conectadas:

1. *Acceso libre*: La disponibilidad de datos en fuentes de acceso libre es creciente. Igualmente la disponibilidad de datos en general, lo cual hace que incrementalmente vamos a requerir herramientas, habilidades que de forma rutinaria nos permiten ingreso y manipulacion de datos de multiples fuentes de información.

2. *Automatización*: R permite un flujo de tranajo adecuado para la implementacion de rutinas de analiss, las cuales una vez estandarizadas pueden ser usadas para analisis repetitivos (rutinarios) o facilmente adaptados para otras situaciones.

3. *Teconología de punta*:  el número y calidad de paquetes de análisis estadistico y epidemiológico en varios lenguajes de programación crece todos los días, y así mismo nos vemos en la necesiad imperiosa de estar al dia en la teconologia mas relevante para la epidemiología y análisis en salud. _R_ permite interaccioón con multiples lenguajes de programacion y por lo tanto es una primera puerta a muchas posibilidades y exploración de varias teconologías de análisis.


4. *Reproducibilidad* la transparencia en el analisis de datos es de creciente importancia en nuestra area. La posibildiad de que los resulatdos que obtenemos sean tan claros que oros investigadores puedan facimente reproducirlos y mejorarlos es un aspecto clave para el avance de la epidemiología.





# Pre-requisitos para este curso

En mi experiencia personal, las caracteristicas maás importantes para aprender un lenguaje de programación sin caer en la frustacioón son: *dedicación* y *atención a los detalles*. La fluencia llegará con la práctica y el tiempo. 

Aunque no existen pre-requisitos como tal, algunos de los conocimientos previos que ayudarán a avanzar más rapidamente en los contenidos de este curso son en su orden:

1. Conocimientos básicos de estadística y matemática. A más conocimiento mejor! 

2. Experiencia en otro lenguaje de programación

3. Conocimientos previos en epidemiología

4. Conocimientos en temas de salud





# Bibliografía


